version: "3"
services:
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - rede-01
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - rede-01
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - rede-01
networks:
  rede-01: