version: "3"
services:
  todofront:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - rede-01
  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    networks:
      - rede-01
  todotests:
    build: ./todo-app/tests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - rede-01
networks:
  rede-01: